From the above data:

Read the data with pandas and find features and target variables
Normalize the data with min-max scaling
Split the data into train and test.

In [ ]:
import pandas as pd
df = pd.read_csv("/content/train.csv")
#print(df)
#1
target = df.columns[-1]
y=df[target]
print(y)
cf =df.drop('price_range',axis=1) # Use 'df' instead of 'data'
print(cf)

#2
bf = cf-cf.min()/(cf.max()-cf.min())
print(bf)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(bf,y,test_size=0.2) # Use column names 'cf' to select features
print(x_train)
print(x_test)
print(y_train)
print(y_test)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64
      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
0        841.665331   0.0          2.0       0.0   1.0     0.0    6.967742
1       1020.665331   1.0          0.3       1.0   0.0     1.0   52.967742
2        562.665331   1.0          0.3       1.0   2.0     1.0   40.967742
3        614.665331   1.0          2.3       0.0   0.0     0.0    9.967742
4       1820.665331   1.0          1.0       0.0  13.0     1.0   43.967742
...             ...   ...          ...       ...   ...     ...         ...
1995     793.665331   1.0          0.3       1.0   0.0     1.0    1.967742
1996    1964.665331   1.0          2.4       1.0   0.0     0.0   38.967742
1997    1910.665331   0.0          0.7       1.0   1.0     1.0   35.967742
1998    1511.665331   0.0          0.7       0.0   4.0     1.0   45.967742
1999     509.665331   1.0          1.8       1.0   5.0     1.0   44.967742

         m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
0     0.488889  187.333333  1.857143   2.0       20.0   755.666222
1     0.588889  135.333333  2.857143   6.0      905.0  1987.666222
2     0.788889  144.333333  4.857143   6.0     1263.0  1715.666222
3     0.688889  130.333333  5.857143   9.0     1216.0  1785.666222
4     0.488889  140.333333  1.857143  14.0     1208.0  1211.666222
...        ...         ...       ...   ...        ...          ...
1995  0.688889  105.333333  5.857143  14.0     1222.0  1889.666222
1996  0.088889  186.333333  3.857143   3.0      915.0  1964.666222
1997  0.588889  107.333333  7.857143   3.0      868.0  1631.666222
1998 -0.011111  144.333333  4.857143   5.0      336.0   669.666222
1999  0.788889  167.333333  5.857143  16.0      483.0   753.666222

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
0     2548.931587   8.642857   7.0  18.888889      0.0           0.0   1.0
1     2630.931587  16.642857   3.0   6.888889      1.0           1.0   0.0
2     2602.931587  10.642857   2.0   8.888889      1.0           1.0   0.0
3     2768.931587  15.642857   8.0  10.888889      1.0           0.0   0.0
4     1410.931587   7.642857   2.0  14.888889      1.0           1.0   0.0
...           ...        ...   ...        ...      ...           ...   ...
1995   667.931587  12.642857   4.0  18.888889      1.0           1.0   0.0
1996  2031.931587  10.642857  10.0  15.888889      1.0           1.0   1.0
1997  3056.931587   8.642857   1.0   4.888889      1.0           1.0   0.0
1998   868.931587  17.642857  10.0  18.888889      1.0           1.0   1.0
1999  3918.931587  18.642857   4.0   1.888889      1.0           1.0   1.0

[2000 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1318    1274.665331   1.0          0.3       1.0   3.0     1.0    4.967742
412     1477.665331   1.0          0.6       1.0  12.0     0.0   47.967742
483     1475.665331   0.0          0.3       0.0   0.0     1.0   42.967742
786      773.665331   1.0          2.6       0.0   7.0     1.0   54.967742
1489     771.665331   1.0          1.0       1.0   7.0     1.0    7.967742
...             ...   ...          ...       ...   ...     ...         ...
1567     939.665331   0.0          2.7       0.0   0.0     0.0   15.967742
550     1407.665331   1.0          1.9       1.0  10.0     0.0   44.967742
1246     533.665331   1.0          2.3       0.0   1.0     1.0   20.967742
755     1017.665331   1.0          0.5       1.0   7.0     0.0   62.967742
248      956.665331   1.0          2.3       0.0   4.0     0.0    6.967742

         m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
1318  0.088889  151.333333  0.857143   9.0       19.0   500.666222
412   0.588889   98.333333  4.857143  17.0      694.0   881.666222
483   0.588889  147.333333  1.857143   2.0     1789.0  1971.666222
786   0.788889  123.333333  2.857143  18.0        8.0   895.666222
1489  0.488889  133.333333  6.857143   8.0      552.0  1801.666222
...        ...         ...       ...   ...        ...          ...
1567  0.588889  114.333333  3.857143   1.0      499.0  1089.666222
550   0.788889   88.333333  4.857143  14.0      613.0  1087.666222
1246  0.188889  163.333333  6.857143   9.0      347.0  1476.666222
755  -0.011111  154.333333  4.857143  18.0      856.0   882.666222
248   0.688889  106.333333  4.857143  10.0     1201.0  1484.666222

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1318  3783.931587  12.642857   4.0   3.888889      1.0           1.0   0.0
412   1140.931587   4.642857   2.0   5.888889      0.0           0.0   1.0
483   3643.931587  14.642857  10.0   5.888889      1.0           0.0   1.0
786   3915.931587   7.642857   1.0  11.888889      1.0           1.0   0.0
1489   421.931587   6.642857   6.0  14.888889      1.0           0.0   0.0
...           ...        ...   ...        ...      ...           ...   ...
1567  2191.931587  14.642857  13.0   8.888889      1.0           1.0   1.0
550   3951.931587   7.642857   6.0   2.888889      0.0           0.0   1.0
1246  2705.931587   6.642857   5.0  17.888889      1.0           1.0   0.0
755   3047.931587   9.642857   3.0   1.888889      0.0           0.0   1.0
248   1845.931587  11.642857   5.0   6.888889      1.0           0.0   1.0

[1600 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
1132    1523.665331   1.0          1.6       1.0   0.0     0.0    9.967742
1018     999.665331   1.0          0.3       0.0  12.0     0.0   62.967742
828     1964.665331   0.0          0.3       0.0   6.0     1.0    3.967742
317     1169.665331   1.0          0.7       0.0   6.0     1.0   13.967742
1194    1298.665331   0.0          2.6       1.0   2.0     0.0   59.967742
...             ...   ...          ...       ...   ...     ...         ...
1286     583.665331   1.0          1.6       0.0   0.0     1.0   18.967742
1067    1702.665331   1.0          0.3       0.0   5.0     1.0   22.967742
1129    1561.665331   1.0          1.0       1.0   0.0     1.0   51.967742
1474    1616.665331   1.0          2.4       0.0  14.0     0.0   28.967742
127     1563.665331   0.0          2.1       0.0   4.0     1.0   24.967742

         m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
1132  0.488889  173.333333  3.857143   1.0      154.0   549.666222
1018  0.588889  178.333333  7.857143  18.0     1537.0  1760.666222
828   0.888889   83.333333  6.857143   9.0      977.0  1659.666222
317   0.288889  198.333333  1.857143  13.0      474.0   708.666222
1194  0.688889  186.333333  7.857143   6.0     1333.0  1837.666222
...        ...         ...       ...   ...        ...          ...
1286  0.188889  167.333333  2.857143   0.0     1123.0  1621.666222
1067  0.088889   91.333333  5.857143   7.0      134.0   520.666222
1129 -0.011111  104.333333  6.857143   9.0      480.0   727.666222
1474  0.788889  112.333333  5.857143  20.0      283.0   675.666222
127   0.388889  188.333333  5.857143  17.0     1259.0  1964.666222

              ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
1132  2677.931587  15.642857   5.0  12.888889      1.0           0.0   1.0
1018  3743.931587  10.642857   1.0   6.888889      0.0           0.0   1.0
828   3534.931587  16.642857   0.0  15.888889      1.0           1.0   1.0
317    714.931587  17.642857   5.0  19.888889      1.0           0.0   1.0
1194  1411.931587  12.642857   1.0  19.888889      0.0           1.0   1.0
...           ...        ...   ...        ...      ...           ...   ...
1286   464.931587  11.642857   8.0   3.888889      1.0           1.0   0.0
1067   792.931587   6.642857   3.0  16.888889      1.0           1.0   0.0
1129  2828.931587  12.642857  10.0   2.888889      1.0           1.0   1.0
1474  3684.931587  12.642857   1.0  17.888889      0.0           0.0   0.0
127   1495.931587   5.642857   4.0   6.888889      1.0           1.0   1.0

[400 rows x 20 columns]
1318    3
412     1
483     3
786     3
1489    0
       ..
1567    1
550     3
1246    2
755     2
248     1
Name: price_range, Length: 1600, dtype: int64
1132    2
1018    3
828     3
317     0
1194    1
       ..
1286    0
1067    0
1129    2
1474    3
127     1
Name: price_range, Length: 400, dtype: int64

Download the dataset from the above link.

Read the data with pandas and describe the data
Find data type and shape of each column
Find the target and features
Find the null values (if yes fill the null values with ‘0’ or mean of that column)
Normalize all the features
Split the data into train and test.

In [ ]:
import pandas as pd
data=pd.read_csv("/content/train.csv")
print(data)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [3]:
#question2
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
print(df)
#1
print(df.describe())
#2
print(df.dtypes)
print(df.shape)

#3
#TARGET
y = df['median_house_value']
print(y)
#FEATURES
x=df.drop('median_house_value',axis=1)
print(x)
#4
null=df.isnull()
null
#5
normalised=df-x.min()/x.max()-x.min()
normalised
#6
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(normalised,y,test_size=0.2,random_state=30)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]
          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000
longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object
(17000, 9)
0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income
0          1015.0       472.0         1.4936
1          1129.0       463.0         1.8200
2           333.0       117.0         1.6509
3           515.0       226.0         3.1917
4           624.0       262.0         1.9250
...           ...         ...            ...
16995       907.0       369.0         2.3571
16996      1194.0       465.0         2.5179
16997      1244.0       456.0         3.0313
16998      1298.0       478.0         1.9797
16999       806.0       270.0         3.0147

[17000 rows x 8 columns]
        households  housing_median_age  latitude  longitude  \
7303    295.999836           46.980769  0.674315   4.922169
12831   408.999836           17.980769  3.914315   1.452169
13976   240.999836           27.980769  4.354315   1.222169
3268    550.999836           28.980769  0.414315   5.402169
7206    171.999836           45.980769  0.684315   4.932169
...            ...                 ...       ...        ...
500    1289.999836           18.980769 -0.485685   6.272169
12077   169.999836           34.980769  5.864315   1.832169
15277   216.999836           50.980769  4.564315   0.982169
4517    295.999836           14.980769  0.444315   5.222169
5925   1104.999836           45.980769  0.784315   5.052169

       median_house_value  median_income   population  total_bedrooms  \
7303                  NaN       4.279274   915.999916      333.999845
12831                 NaN       5.784574  1493.999916      425.999845
13976                 NaN       5.516874   686.999916      249.999845
3268                  NaN       3.186974  3245.999916      570.999845
7206                  NaN       1.800074   412.999916      185.999845
...                   ...            ...          ...             ...
500                   NaN       2.664674  3683.999916     1324.999845
12077                 NaN       1.633474   500.999916      182.999845
15277                 NaN       3.383474   485.999916      213.999845
4517                  NaN       6.554674   874.999916      261.999845
5925                  NaN       2.504474  3344.999916     1269.999845

       total_rooms
7303   2006.999947
12831  2632.999947
13976  1691.999947
3268   2648.999947
7206    822.999947
...            ...
500    6693.999947
12077  1121.999947
15277  1169.999947
4517   2067.999947
5925   5074.999947

[13600 rows x 9 columns]
       households  housing_median_age  latitude  longitude  \
10914  631.999836            3.980769  4.194315   2.412169
6241   368.999836           35.980769  0.914315   5.012169
5904   604.999836           45.980769  0.474315   5.062169
9578   590.999836           37.980769  3.204315   3.912169
9444   201.999836           32.980769  0.984315   4.012169
...           ...                 ...       ...        ...
12228  242.999836           50.980769  5.234315   1.792169
6639   160.999836           39.980769  0.594315   4.982169
7850   708.999836            8.980769  1.384315   4.862169
4886   296.999836           40.980769  0.694315   5.162169
3618   201.999836           25.980769  0.294315   5.352169

       median_house_value  median_income   population  total_bedrooms  \
10914                 NaN       1.695974  1589.999916      743.999845
6241                  NaN       4.552974   963.999916      366.999845
5904                  NaN       2.480274  1384.999916      624.999845
9578                  NaN       2.111274  2195.999916      606.999845
9444                  NaN       4.349174   441.999916      218.999845
...                   ...            ...          ...             ...
12228                 NaN       1.490974   557.999916      293.999845
6639                  NaN       2.121374   638.999916      131.999845
7850                  NaN       3.760874  2160.999916      812.999845
4886                  NaN       2.896474  1001.999916      296.999845
3618                  NaN       5.386374   431.999916      341.999845

       total_rooms
10914  2896.999947
6241   1951.999947
5904   2546.999947
9578   3024.999947
9444   1186.999947
...            ...
12228  1381.999947
6639    617.999947
7850   4119.999947
4886   1433.999947
3618   1794.999947

[3400 rows x 9 columns]
7303     170500.0
12831    248000.0
13976    254200.0
3268     182100.0
7206     133300.0
           ...
500      154600.0
12077     93800.0
15277    235600.0
4517     338800.0
5925     186800.0
Name: median_house_value, Length: 13600, dtype: float64
10914    127500.0
6241     261300.0
5904     192700.0
9578      62000.0
9444     396400.0
           ...
12228     94600.0
6639     159600.0
7850     151600.0
4886     195800.0
3618     500001.0
Name: median_house_value, Length: 3400, dtype: float64